spring:
  profiles.active: local
  datasource:
    #    hikari:
    url: jdbc:mysql://localhost:3306/teamfresh?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true&socketTimeout=3000&connectTimeout=3000&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user_dev
    password: password
    pool-name: dbcp-main
    minimum-idle: 5
    maximum-pool-size: 5
    connection-timeout: 2500 # 2.5s
    validation-timeout: 2500 # 2.5s
    max-lifetime: 1800000 # 30min. NOTE: RDS wait_timeout: 28.80s
    #      leak-detection-threshold: 11000 # 11s (3rd party client read timeout + 1s)
    transaction-isolation: TRANSACTION_REPEATABLE_READ
    connection-test-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  lifecycle.timeout-per-shutdown-phase: 20s
  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace